name: User Story
description: This template provides a basic structure for user story issues.
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        You may want to read up on [how to write user stories](https://www.nuclino.com/articles/user-story-template-examples)
        before moving ahead with this issue.
  - type: input
    id: user-profile
    attributes:
      label: User Profile
      placeholder: As a...
  - type: textarea
    id: i-want-to
    attributes:
      label: User Action
      placeholder: I want to...
  - type: textarea
    id: so-that
    attributes:
      label: User Goal
      placeholder: So that...
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: This is something that can be verified to show that this user story is satisfied.
  - type: textarea
    id: linked-issue
    attributes:
      label: Linked Issues
      description: Specific issues that need to be resolved to enable this user story
      placeholder: Can be created and updated later...
